### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Venryx** [Kayron013/lexorank-rust#1]
What license is this crate released under? (I'd like to have all the dependencies of my project be open-source, eg. MIT or Apache, so that my entire project can remain so.)

Note: I've added this crate to a list of fractional-indexing/lexorank libraries here: https://gist.github.com/Venryx/8e1c26cce0959f201b2d2080587c112b

**Comment by Kayron013** [comment]
I've added the ISC license to the project. Thank you for asking.
